package speculative;

import java.io.BufferedReader;
import java.io.FileReader;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class Train {

    /*
     * Loads parse trees generated by Parser
     * Splits data into training and test sets
     * Trains Sentiment Analysis model
     */ 
    public static void main(String[] args) throws Exception {

        String inFile = "res/parsed.txt";
        String outFile = "res/model.txt";

        for (int argIndex = 0; argIndex < args.length; argIndex++) {
            if (args[argIndex].equalsIgnoreCase("-input")) {
                inFile = args[++argIndex];
            } else if (args[argIndex].equalsIgnoreCase("-output")) {
                outFile = args[++argIndex];
            } else {
                System.err.println("Unknown argument " + args[argIndex]);
                System.exit(2);
            }
        }

        // Load parse trees generated by Parser
        List<String> sentences = new ArrayList<String>();
        FileReader file = new FileReader(inFile);
        BufferedReader binfile = new BufferedReader(file);
        String sentence = binfile.readLine();
        while (sentence != null) {
            sentences.add(sentence);
            sentence = binfile.readLine();
        }
        binfile.close();

        // Generate training/test data
        Collections.shuffle(sentences);
        int trainingSize = sentences.size()/2;
        int testSize = Math.min(500, sentences.size() - trainingSize);
        List<String> trainingData = sentences.subList(0, trainingSize);
        List<String> testData = sentences.subList(trainingSize, trainingSize + testSize);

        // Train sentiment analysis model
        // TODO
    }

}
